### PR TITLE
[CF-345/CF-347] Stale connections

### PR DESCRIPTION
**Pull request by ChandraAddala**
- Added extra properties for c3p0 to test connection on checkout by running a query we provide
  - Configured to see c3p0 logging in log files.
  - upgraded c3p0 version

### CODE REVIEW

**Comment by shintasmith** [comment]
looks good, lets try it out

**Comment by mwhahaha** [comment]
I can vouch that these settings work.  I've already applied them to the various environments in puppet.  I'll update the logback configs as well.

**Comment by shintasmith** [comment]
oh, @mwhahaha, I asked @ChandraAddala this yesterday. These settings to do connection tests between app and DB, I know we use it in Feeds. But isn't that going to generate lots of chit-chat between the app nodes and the DBs? You don't see that as a big problem, I guess?

**Comment by mwhahaha** [comment]
It shouldn't generate more chitchat than normal.  The connection test will add an extra query but it's a simple select 1.  The idle check is only every 2 minutes so it won't add much in terms of idle talk.  For this service, these added configuration items shouldn't add much in terms of performance overhead.  If the service gets consistent traffic then we can look at removing these, but without these settings we will be generating 500s often due to connection issues.

**Comment by shintasmith** [comment]
ok sounds good

**Pull request merged**
